default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  username: root
  password: ""

development:
  <<: *default
  database: cryptocompare_development
  variables:
    sql_mode: TRADITIONAL

test:
  <<: *default
  database: cryptocompare_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: cryptocompare
  username: root
  password: 'Yuu,3a7&T2'
  variables:
    sql_mode: TRADITIONAL
